name: day 4 part 2

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'develop'
    paths:
      - 'days/day4-part2/**'

env:
  DIRECTORY: 'days/day4-part2'

jobs:
  job:
    name: Job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: 'maven'
      - name: Build Project
        working-directory: ${{ env.DIRECTORY }}
        run: mvn clean install -T 2
      - name: Run Project
        working-directory: ${{ env.DIRECTORY }}
        run: java -jar target/task.jar